### ISSUE TITLE
[dev-end] load_public_dataset is broken

### ISSUE THREAD

**Issue by tbrnd** [tournesol-app/tournesol#1328]
Hi everyone,

`load_public_dataset` seems to be broken.

Current branch:  `main` commit `c9c3b9dab`
How to reproduce:

```
$ ./run-docker-compose.sh download --user-sampling 0.1 
 ⠿ Container tournesol-dev-api    Started                                 25.9s
Waiting for api to be ready...
Waiting for api to be ready...
Waiting for api to be ready...
Waiting for api to be ready...
Waiting for api to be ready...
Waiting for api to be ready...

 Created 534 users
Created 5113 video entities
Traceback (most recent call last):
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3621, in get_loc
    return self._engine.get_loc(casted_key)
  File "pandas/_libs/index.pyx", line 136, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/index.pyx", line 163, in pandas._libs.index.IndexEngine.get_loc
  File "pandas/_libs/hashtable_class_helper.pxi", line 5198, in pandas._libs.hashtable.PyObjectHashTable.get_item
  File "pandas/_libs/hashtable_class_helper.pxi", line 5206, in pandas._libs.hashtable.PyObjectHashTable.get_item
KeyError: 'weight'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/backend/manage.py", line 22, in <module>
    main()
  File "/backend/manage.py", line 18, in main
    execute_from_command_line(sys.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 446, in execute_from_command_line
    utility.execute()
  File "/usr/local/lib/python3.9/site-packages/django/core/management/__init__.py", line 440, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 414, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/usr/local/lib/python3.9/site-packages/django/core/management/base.py", line 460, in execute
    output = self.handle(*args, **options)
  File "/backend/tournesol/management/commands/load_public_dataset.py", line 113, in handle
    weight=values["weight"],
  File "/usr/local/lib/python3.9/site-packages/pandas/core/series.py", line 958, in __getitem__
    return self._get_value(key)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/series.py", line 1069, in _get_value
    loc = self.index.get_loc(label)
  File "/usr/local/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 3623, in get_loc
    raise KeyError(key) from err
```

I will investigate but any help is welcome!

**Comment by amatissart** [comment]
argh probably caused by #1323 
We talked about how removing a column could break existing third-party scripts, but forgot our own scripts could also be affected :upside_down_face:
